apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuroplan-test
  namespace: neuroplan

spec:
  replicas: 2

  selector:
    matchLabels:
      app: neuroplan-test

  template:
    metadata:
      labels:
        app: neuroplan-test

    spec:
      containers:
        - name: neuroplan-test
          image: yerinnn/neuroplan-ci-test:5
          ports:
            - containerPort: 80
